function Hd = notch_filt_1
%NOTCH_FILT_1 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
%
% Generated on: 29-Nov-2008 13:14:11
%

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 2016;  % Sampling Frequency

Fpass1 = 55;              % First Passband Frequency
Fstop1 = 59;              % First Stopband Frequency
Fstop2 = 61;              % Second Stopband Frequency
Fpass2 = 65;              % Second Passband Frequency
Dpass1 = 0.028774368332;  % First Passband Ripple
Dstop  = 0.001;           % Stopband Attenuation
Dpass2 = 0.057501127785;  % Second Passband Ripple
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass1 Fstop1 Fstop2 Fpass2]/(Fs/2), [1 0 ...
                          1], [Dpass1 Dstop Dpass2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
